[package]
name = "sfs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sfs"
path = "src/main.rs"

[[bin]]
name = "benchmark_indexing"
path = "src/bin/benchmark_indexing.rs"

[[bin]]
name = "profile_file"
path = "src/bin/profile_file.rs"

[[bin]]
name = "benchmark_tree_sitter"
path = "src/bin/benchmark_tree_sitter.rs"

[[bin]]
name = "test_tree_sitter_symbols"
path = "src/bin/test_tree_sitter_symbols.rs"

[[bin]]
name = "test_content_search"
path = "src/bin/test_content_search.rs"

[[bin]]
name = "test_backend_detection"
path = "src/bin/test_backend_detection.rs"

[dependencies]
# TUI
ratatui = "0.24"
crossterm = "0.27"

# Tree-sitter
tree-sitter = "0.20"
tree-sitter-typescript = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-python = "0.20"
# Popular web/systems languages
tree-sitter-php = "0.20"
tree-sitter-ruby = "0.20"
tree-sitter-go = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-java = "0.20"
# Additional languages
tree-sitter-c = "0.20"
tree-sitter-cpp = "0.20"
tree-sitter-c-sharp = "0.20"
tree-sitter-scala = "0.20"

# 検索・ファイル操作
fuzzy-matcher = "0.3"
globwalk = "0.8"
ignore = "0.4"        # .gitignore対応
glob = "0.3"          # パターンマッチング

# クリップボード
arboard = "3.2"

# CLI・設定
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 非同期・並列処理
tokio = { version = "1.0", features = ["full"] }
rayon = "1.8"

# エラーハンドリング
anyhow = "1.0"
thiserror = "1.0"

# 外部ツール統合
which = "4.4"         # ツール検出

# ファイルシステム監視
notify = "6.1"        # リアルタイムファイル監視

# 正規表現・ランダム
regex = "1.10"
rand = "0.8"

# キャッシュ機能
sha2 = "0.10"         # ファイルハッシュ計算
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0"        # gzip圧縮・展開
lru = "0.12"          # LRUキャッシュ

[dev-dependencies]
criterion = "0.5"     # ベンチマーク
tempfile = "3.8"      # テスト用
mockall = "0.12"      # モック生成
serial_test = "3.0"   # テスト実行順序制御

[[bench]]
name = "indexing_performance"
harness = false

[[bench]]
name = "search_performance"
harness = false
